### PR TITLE
Updated for Swift 5

### PR DESCRIPTION
**Pull request by gaetandezeiraud**

### CODE REVIEW

**Comment by 0xWDG** [comment]
Nice PR! 😊

**Comment by gaetandezeiraud** [comment]
I am sad, I have the bad impression that the project is abandoned. :'(

**Comment by 0xWDG** [comment]
I'm afraid also, shall we otherwise update the project in a Fork, since now for already 2 years there is no action.

**Comment by gaetandezeiraud** [comment]
I think the same. But I did not find information on the license of the project. So, I don't know if it's possible to fork the project and set a licence on it without knowing the current.

**Comment by 0xWDG** [comment]
True, but since there is no contact with the repo owner (does not respond on pull requests, or issues). 
I don't think it's a problem.

I have some ideas for the project, which I will commit to my fork, feel free to commit there if you want.

**Comment by 0xWDG** [comment]
I've append your patch at https://github.com/wdg/CodeEditor

**Pull request closed without merging**
